name: Dev Pipeline
on:
  push:
    branches:
      - 'bugfix/**'
      - 'feature/**'
jobs:
  build_deploy:
    if: github.repository != 'twentyfourg/vue-template'
    name: Dev Build/Deploy
    runs-on: ubuntu-latest
    environment: dev
    env:
      VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
      VAULT_ROLE: ${{ secrets.VAULT_ROLE }}
      VAULT_ADDR: 'https://vault.24g.dev'
      SECRET_PATH: ${{ secrets.SECRET_PATH }}
    steps:
      - uses: actions/checkout@v2
      - name: Vault Pipeline Auth
        id: vault_aws
        uses: twentyfourg/vault-aws-action@1.0.0
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ steps.vault_aws.outputs.access_key }}
          aws-secret-access-key: ${{ steps.vault_aws.outputs.secret_key }}
          aws-session-token: ${{ steps.vault_aws.outputs.session_token }}
          aws-region: us-east-1
      - name: Install Node dependencies
        run: npm install
      - name: Vue Build
        run: npm run build-dev
      - name: S3 Sync
        run: aws s3 sync $SOURCE_DIR s3://$AWS_S3_BUCKET --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.S3_BUCKET }}
          SOURCE_DIR: './dist/'
      # Only invalidate CloudFront if caching is enabled.
      # Can't use the secret context [1] in a conditional directly
      - name: Invalidate CloudFront
        env:
          CACHE_ENABLED: ${{ secrets.CACHE_ENABLED }}
        run: |
          if [ "$CACHE_ENABLED" == "true" ]
            then
              echo "Invalidating Cache:"
              aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_ID }} --paths "/index.html" "/static/*"
            else
              echo "Caching is disabled. No need to Invalidate."
          fi

# [1]: https://github.com/actions/runner/issues/520
