name: Dev Pipeline
on:
  push:
    branches:
      - 'bugfix/**'
      - 'feature/**'
jobs:
  build_deploy:
    name: Dev Build/Deploy
    runs-on: ubuntu-latest
    env:
      VAULT_TOKEN: ${{ secrets.DEV_VAULT_TOKEN }}
      VAULT_ROLE: ${{ secrets.DEV_VAULT_ROLE }}
      VAULT_ADDR: 'https://vault.24g.dev'
      SECRET_PATH: ${{ secrets.DEV_SECRET_PATH }}
    steps:
      - uses: actions/checkout@v2
      - name: Vault Pipeline Auth
        id: vault_aws
        uses: twentyfourg/vault-aws-action@1.0.0
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ steps.vault_aws.outputs.access_key }}
          aws-secret-access-key: ${{ steps.vault_aws.outputs.secret_key }}
          aws-session-token: ${{ steps.vault_aws.outputs.session_token }}
          aws-region: us-east-1
      - name: Install Node dependencies
        run: npm install
      - name: Vue Build
        run: npm run build-dev
      - name: S3 Sync
        run: aws s3 sync $SOURCE_DIR s3://$AWS_S3_BUCKET --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.DEV_S3_BUCKET }}
          SOURCE_DIR: './dist/'
